on:
  release:
    types: [published]

name: Publish

jobs:
  zip-files:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: dist
          recursive: false
          dest: TheWholesomeHaciendaOverhaul.zip